-- Kampala Nonstop / Africa Nonstop
-- V0 Waitlist Schema
-- PostgreSQL
--
-- Design conventions:
--   * Primary keys are UUIDs generated by the application (Laravel UUIDv7).
--   * created_at / updated_at use TIMESTAMPTZ.
--   * ISO 3166-1 alpha-2 country codes are stored as CHAR(2).
--   * countries_of_interest is a PostgreSQL CHAR(2)[] array.
--   * V0 defaults countries_of_interest to Uganda ('UG').
--   * Invitation acceptance/conversion is derived by business logic; no status/accepted_at fields.
--   * An invitation may be sent by EITHER a waitlist member OR a registered user, never both.

BEGIN;

-- -----------------------------------------------------------------------------
-- Helper trigger: keep updated_at current on UPDATE.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION kn_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- acquisition_sources
-- Shared controlled source/campaign attribution lookup.
-- Examples: website, instagram, nn_brussels_2026, afcon_2027.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS acquisition_sources (
    id          UUID PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    code        VARCHAR(100) NOT NULL UNIQUE,
    type        VARCHAR(50)  NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_acquisition_sources_updated_at ON acquisition_sources;
CREATE TRIGGER trg_acquisition_sources_updated_at
BEFORE UPDATE ON acquisition_sources
FOR EACH ROW
EXECUTE FUNCTION kn_set_updated_at();

-- -----------------------------------------------------------------------------
-- interest_types
-- Canonical high-level traveller interests shared with future trip-planner logic.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS interest_types (
    id             UUID PRIMARY KEY,
    name           VARCHAR(150) NOT NULL,
    code           VARCHAR(100) NOT NULL UNIQUE,
    description    TEXT,
    display_order  INTEGER      NOT NULL DEFAULT 0,
    active         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

DROP TRIGGER IF EXISTS trg_interest_types_updated_at ON interest_types;
CREATE TRIGGER trg_interest_types_updated_at
BEFORE UPDATE ON interest_types
FOR EACH ROW
EXECUTE FUNCTION kn_set_updated_at();

-- -----------------------------------------------------------------------------
-- waitlist_signups
-- One row per waitlist signup.
-- country_code = country of residence.
-- countries_of_interest = destination countries of interest; V0 submits ['UG'].
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS waitlist_signups (
    id                     UUID PRIMARY KEY,
    first_name             VARCHAR(100) NOT NULL,
    surname                VARCHAR(100) NOT NULL,
    email                  VARCHAR(254) NOT NULL UNIQUE,
    country_code           CHAR(2)      NOT NULL,
    acquisition_source_id  UUID         NOT NULL,
    marketing_consent      BOOLEAN      NOT NULL DEFAULT FALSE,
    marketing_consent_at   TIMESTAMPTZ,
    unsubscribed           BOOLEAN      NOT NULL DEFAULT FALSE,
    countries_of_interest  CHAR(2)[]    NOT NULL DEFAULT ARRAY['UG']::CHAR(2)[],
    source_details         TEXT,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_waitlist_signups_acquisition_source
        FOREIGN KEY (acquisition_source_id)
        REFERENCES acquisition_sources(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_waitlist_country_code_upper
        CHECK (country_code = UPPER(country_code)),

    CONSTRAINT chk_waitlist_countries_of_interest_not_empty
        CHECK (cardinality(countries_of_interest) > 0)
);

CREATE INDEX IF NOT EXISTS idx_waitlist_signups_acquisition_source_id
    ON waitlist_signups(acquisition_source_id);

CREATE INDEX IF NOT EXISTS idx_waitlist_signups_created_at
    ON waitlist_signups(created_at);

CREATE INDEX IF NOT EXISTS idx_waitlist_signups_countries_of_interest
    ON waitlist_signups USING GIN (countries_of_interest);

DROP TRIGGER IF EXISTS trg_waitlist_signups_updated_at ON waitlist_signups;
CREATE TRIGGER trg_waitlist_signups_updated_at
BEFORE UPDATE ON waitlist_signups
FOR EACH ROW
EXECUTE FUNCTION kn_set_updated_at();

-- -----------------------------------------------------------------------------
-- waitlist_signup_interests
-- Many-to-many link between waitlist signups and canonical interest types.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS waitlist_signup_interests (
    id                  UUID PRIMARY KEY,
    waitlist_signup_id  UUID        NOT NULL,
    interest_type_id    UUID        NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_waitlist_signup_interests_signup
        FOREIGN KEY (waitlist_signup_id)
        REFERENCES waitlist_signups(id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_waitlist_signup_interests_interest
        FOREIGN KEY (interest_type_id)
        REFERENCES interest_types(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_waitlist_signup_interest
        UNIQUE (waitlist_signup_id, interest_type_id)
);

CREATE INDEX IF NOT EXISTS idx_waitlist_signup_interests_signup_id
    ON waitlist_signup_interests(waitlist_signup_id);

CREATE INDEX IF NOT EXISTS idx_waitlist_signup_interests_interest_type_id
    ON waitlist_signup_interests(interest_type_id);

-- -----------------------------------------------------------------------------
-- invitations
-- Records that an invitation was sent.
-- Acceptance / conversion is derived from recipient_email + signup timestamps.
--
-- Exactly one inviter FK must be populated:
--   inviter_waitlist_signup_id -> waitlist_signups.id
--   inviter_user_id            -> users.id (registered user)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS invitations (
    id                          UUID PRIMARY KEY,
    recipient_email             VARCHAR(254) NOT NULL,
    inviter_waitlist_signup_id  UUID,
    inviter_user_id             UUID,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_invitations_waitlist_inviter
        FOREIGN KEY (inviter_waitlist_signup_id)
        REFERENCES waitlist_signups(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_invitations_exactly_one_inviter
        CHECK (
            (inviter_waitlist_signup_id IS NOT NULL AND inviter_user_id IS NULL)
            OR
            (inviter_waitlist_signup_id IS NULL AND inviter_user_id IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS idx_invitations_recipient_email
    ON invitations(recipient_email);

CREATE INDEX IF NOT EXISTS idx_invitations_waitlist_inviter_id
    ON invitations(inviter_waitlist_signup_id)
    WHERE inviter_waitlist_signup_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_invitations_user_inviter_id
    ON invitations(inviter_user_id)
    WHERE inviter_user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_invitations_created_at
    ON invitations(created_at);

DROP TRIGGER IF EXISTS trg_invitations_updated_at ON invitations;
CREATE TRIGGER trg_invitations_updated_at
BEFORE UPDATE ON invitations
FOR EACH ROW
EXECUTE FUNCTION kn_set_updated_at();

-- -----------------------------------------------------------------------------
-- Optional FK to registered users.
-- This is added only if a public.users table already exists with a UUID id column.
-- If your users table has a different schema/table name, replace this block.
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF to_regclass('public.users') IS NOT NULL
       AND EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = 'users'
              AND column_name = 'id'
              AND data_type = 'uuid'
       )
       AND NOT EXISTS (
            SELECT 1
            FROM pg_constraint
            WHERE conname = 'fk_invitations_user_inviter'
       )
    THEN
        ALTER TABLE invitations
            ADD CONSTRAINT fk_invitations_user_inviter
            FOREIGN KEY (inviter_user_id)
            REFERENCES public.users(id)
            ON UPDATE CASCADE
            ON DELETE RESTRICT;
    END IF;
END;
$$;

COMMIT;

-- -----------------------------------------------------------------------------
-- Suggested V0 seed examples (optional; UUIDs intentionally omitted because the
-- application should generate UUIDv7 values).
-- -----------------------------------------------------------------------------
-- acquisition_sources examples:
--   Organic Website / website / organic
--   Instagram       / instagram / social
--   Direct / Unknown / direct_unknown / direct
--
-- interest_types examples:
--   Culture & Heritage                  / culture_heritage
--   Food & Local Life                   / food_local_life
--   Music, Nightlife & Entertainment    / music_nightlife_entertainment
--   Nature & Wildlife                   / nature_wildlife
--   Adventure & Outdoors                / adventure_outdoors
--   Events & Festivals                  / events_festivals
--   Wellness & Relaxation               / wellness_relaxation
--   Sports & Recreation                 / sports_recreation
--   Other                               / other
