-- Kampala Nonstop / Africa Nonstop
-- Uganda Local Knowledge sample content
-- PostgreSQL
--
-- Canonical population is database/seeders/LocalKnowledgeUgandaSeeder.php
-- (47 live items across all six types, with tags and page-context links).
-- This script mirrors that seeder for non-Laravel environments.
--
-- Prerequisite: 6_1 lookup seed and geographic areas must already exist.
-- Idempotent: matches on (country_code, title).

BEGIN;

WITH items (
    type_code,
    title,
    content,
    explanation,
    language_code,
    area_code,
    source_url,
    is_live
) AS (
    VALUES
        ('CULTURAL_CONTEXT', 'Buganda hospitality', 'Kampala sits in Buganda, historically a powerful kingdom. Politeness, greeting rituals and respect for elders still shape everyday interaction, even in a busy capital.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'Church and mosque side by side', 'Uganda is religiously mixed: Christianity is the majority, Islam is well established, and traditional practice continues. Friday prayers and Sunday services both shape the city’s rhythm.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'Kampala after dark', 'Nightlife clusters in areas such as Kabalagala, Kololo and the city centre. Live music and outdoor bars run late on weekends; weeknights are quieter but not empty.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'Markets set the price conversation', 'In markets, a first quoted price is often an opening. Stay friendly, know a rough fair range, and be willing to walk away. Supermarkets and malls are fixed-price.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'Matooke on the table', 'Steamed green bananas — matooke — are the staple of central Uganda. Served mashed with a groundnut or meat sauce, it is comfort food rather than a tourist dish.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'Tea and coffee country', 'Uganda grows both tea and specialty coffee. A cup in Kampala is everyday fuel; a visit to a Mount Elgon or western coffee farm is a trip in its own right.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'The Rolex is not a watch', 'A Rolex is Uganda’s iconic street wrap: chapati rolled around eggs, cabbage and tomato. Cheap, filling, and available from roadside stoves from breakfast until late.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Ask before photographing people', 'Always ask before photographing people, especially in markets, places of worship and rural communities. A nod and a greeting usually suffice; some vendors will expect a small purchase.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Greet before you ask', 'Start with a greeting before a request — even a short “hello, how are you?” Matters in shops, taxis and offices. Jumping straight to business can read as abrupt.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Modest dress at religious sites', 'Cover shoulders and knees for mosques, churches and traditional shrines. Kampala streetwear is relaxed; sacred spaces are not.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Patience with time', 'Appointments can run late without anyone treating it as a crisis. Build buffer into plans, especially around Kampala traffic, and stay polite rather than pushing.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Public affection', 'Kampala is more relaxed than rural Uganda, but overt public affection still draws attention. A little discretion is the local default.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Right hand for exchange', 'Give and receive money, food and gifts with your right hand, or with both hands. The left hand is still considered less polite for that kind of exchange.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Tipping is a thank-you, not a bill', 'Tipping is appreciated rather than automatic. Rounding up a taxi fare, leaving 5–10% in a sit-down restaurant, or a small cash thank-you to a guide is typical.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'A young country', 'Uganda has one of the youngest populations in the world. That energy shows up in Kampala’s music, start-ups, nightlife and street food as much as in official statistics.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Boda boda origin', '“Boda boda” originally described border-to-border motorcycle taxis. In Kampala it now means almost any motorbike-for-hire weaving through traffic.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Equator crossing', 'The equator crosses Uganda just south of Kampala. Many travellers stop at the marked crossing on the Kampala–Masaka road for photos and the classic water-drain demonstration.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Fifty-plus languages', 'Uganda has more than 50 living languages. English is official, Swahili is a second official language, and Luganda is the one you will hear most around Kampala.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Lake Victoria scale', 'Lake Victoria is Africa’s largest lake by area. Entebbe sits on its northern shore, which is why the international airport feels more lakeside town than inland capital.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Mountain gorillas', 'Uganda is one of only a handful of countries where you can trek to see mountain gorillas, mainly in Bwindi Impenetrable National Park and Mgahinga in the south-west.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Pearl of Africa', 'Winston Churchill called Uganda the “Pearl of Africa” after travelling through East Africa in 1907 — the nickname still fits the lakes, hills and wildlife packed into a relatively small country.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Source of the Nile', 'Jinja, on Lake Victoria, is widely recognised as the source of the Nile — the river then runs north through Uganda before continuing towards the Mediterranean.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Forex beats the hotel desk', 'Kampala forex bureaux on Kampala Road and around Nakasero usually beat hotel exchange rates. Count your notes at the window; reputable desks are used to visitors doing exactly that.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Leave Kampala before the Friday rush', 'If you are heading west to Queen Elizabeth or Bwindi, leave Kampala early on Friday — or better, Thursday. Weekend traffic on the Masaka road can erase a whole afternoon.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Murchison is closer than it feels', 'Murchison Falls is a long day from Kampala, but an overnight turns it from a rush into the classic Nile-and-savannah trip most first-time visitors actually want.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Owino for the real city', 'St. Balikuddembe Market (Owino) is chaotic, cheap and local. Go with a guide or a Kampala friend the first time; it is the opposite of a mall, and that is the point.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Share your live location on night rides', 'For late boda or taxi rides, share a live location with someone. It is normal caution rather than alarmism, and drivers used to visitors will not take offence.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Sim-sim and muchomo after dark', 'Roadside muchomo (grilled meat) and sim-sim (sesame) snacks appear as the sun drops. Follow the busiest stall rather than the quietest — turnover is your hygiene cue.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Sipi over the obvious waterfall stop', 'If you have a spare day in the east, Sipi Falls on the slopes of Mount Elgon is the overnight people remember — coffee tours, cliff views and cooler air than Kampala.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Sunset at the lake, not the mall', 'For a first evening, skip the mall food court and go to a lakeside spot in Entebbe or Ggaba. Kampala’s hills are dramatic; the lake is where the day actually ends.', NULL, NULL, NULL, NULL, TRUE),
        ('PHRASE', 'Asante', 'Asante', 'Swahili for “thank you.” Asante sana means “thank you very much.” Handy beyond Kampala, especially towards Kenya and Tanzania.', 'sw', NULL, NULL, TRUE),
        ('PHRASE', 'Jambo', 'Jambo', 'A Swahili hello used across East Africa. English is more common in Kampala, but Jambo still works as a friendly, widely understood greeting.', 'sw', NULL, NULL, TRUE),
        ('PHRASE', 'Kale', 'Kale', 'A flexible Luganda yes / OK / alright. You will hear it constantly in Kampala conversation as agreement or a soft close to a discussion.', 'lg', NULL, NULL, TRUE),
        ('PHRASE', 'Mzungu', 'Mzungu', 'A Swahili-origin word for a foreigner, especially a white visitor. It is usually descriptive rather than hostile; a smile and a greeting still go a long way.', 'sw', NULL, NULL, TRUE),
        ('PHRASE', 'Oli otya?', 'Oli otya?', 'The everyday Luganda greeting: “How are you?” A typical reply is “Gyendi” (I’m fine). Using it, even once, usually gets a warmer response than jumping straight to English.', 'lg', NULL, NULL, TRUE),
        ('PHRASE', 'Ssebo and Nnyabo', 'Ssebo / Nnyabo', 'Polite Luganda forms of address: Ssebo for a man, Nnyabo for a woman. Useful with taxi drivers, market vendors and hotel staff.', 'lg', NULL, NULL, TRUE),
        ('PHRASE', 'Tusanyuse okukulaba', 'Tusanyuse okukulaba', '“We are happy to see you.” A warm welcome you may hear from hosts — worth recognising even if you do not say it yourself.', 'lg', NULL, NULL, TRUE),
        ('PHRASE', 'Webale', 'Webale', 'Luganda for “thank you.” Add “nyo” for “thank you very much”: Webale nyo.', 'lg', NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Agree the boda fare first', 'Agree the fare before you sit on a boda boda. Ride-hailing apps (SafeBoda, Uber, Bolt) remove most of that negotiation in Kampala and keep a record of the trip.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Buy a local SIM on arrival', 'MTN and Airtel kiosks sit just after baggage reclaim at Entebbe. Bring your passport. Data is inexpensive and coverage is strong in Kampala and major towns.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Cash still matters', 'Cards work in many hotels, restaurants and supermarkets in Kampala. Carry some Ugandan shillings anyway — markets, bodas and smaller eateries are still cash-first.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Drink bottled or treated water', 'Stick to sealed bottled water or a filter bottle. Ice in established restaurants is usually fine; be more cautious with street-side juices if you have a sensitive stomach.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Entebbe to Kampala takes longer than the map suggests', 'The airport is about 40 km from Kampala. In light traffic that can be 45–60 minutes; in the evening peak it can double. Build slack around flight times.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Mobile money is everywhere', 'MTN MoMo and Airtel Money booths are on almost every Kampala street. Locals use them for everything from school fees to market stalls. Visitors can often pay a vendor who then pays onward by mobile money.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Pack a Type G adapter', 'Uganda uses Type G sockets (the UK three-pin) at 240 V. A single adapter covers hotels, offices and most guesthouses.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Two rainy seasons, not a monsoon', 'Kampala’s wetter months are roughly March–May and September–November. Rain often arrives as a heavy burst rather than an all-day washout — a light jacket still earns its bag space.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Yellow fever certificate', 'A yellow fever vaccination certificate is commonly requested on entry. Keep it with your passport rather than packed in hold luggage.', NULL, NULL, NULL, NULL, TRUE)
)
UPDATE local_knowledge AS lk
SET
    local_knowledge_type_id = t.id,
    content = i.content,
    explanation = i.explanation,
    local_language_code = i.language_code,
    geographic_area_id = a.id,
    source_url = i.source_url,
    is_live = i.is_live,
    updated_at = CURRENT_TIMESTAMP
FROM items i
JOIN local_knowledge_types t ON t.code = i.type_code
LEFT JOIN geographic_areas a ON a.code = i.area_code
WHERE lk.country_code = 'UG'
  AND lk.title = i.title;

WITH items (
    type_code,
    title,
    content,
    explanation,
    language_code,
    area_code,
    source_url,
    is_live
) AS (
    VALUES
        ('CULTURAL_CONTEXT', 'Buganda hospitality', 'Kampala sits in Buganda, historically a powerful kingdom. Politeness, greeting rituals and respect for elders still shape everyday interaction, even in a busy capital.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'Church and mosque side by side', 'Uganda is religiously mixed: Christianity is the majority, Islam is well established, and traditional practice continues. Friday prayers and Sunday services both shape the city’s rhythm.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'Kampala after dark', 'Nightlife clusters in areas such as Kabalagala, Kololo and the city centre. Live music and outdoor bars run late on weekends; weeknights are quieter but not empty.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'Markets set the price conversation', 'In markets, a first quoted price is often an opening. Stay friendly, know a rough fair range, and be willing to walk away. Supermarkets and malls are fixed-price.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'Matooke on the table', 'Steamed green bananas — matooke — are the staple of central Uganda. Served mashed with a groundnut or meat sauce, it is comfort food rather than a tourist dish.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'Tea and coffee country', 'Uganda grows both tea and specialty coffee. A cup in Kampala is everyday fuel; a visit to a Mount Elgon or western coffee farm is a trip in its own right.', NULL, NULL, NULL, NULL, TRUE),
        ('CULTURAL_CONTEXT', 'The Rolex is not a watch', 'A Rolex is Uganda’s iconic street wrap: chapati rolled around eggs, cabbage and tomato. Cheap, filling, and available from roadside stoves from breakfast until late.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Ask before photographing people', 'Always ask before photographing people, especially in markets, places of worship and rural communities. A nod and a greeting usually suffice; some vendors will expect a small purchase.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Greet before you ask', 'Start with a greeting before a request — even a short “hello, how are you?” Matters in shops, taxis and offices. Jumping straight to business can read as abrupt.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Modest dress at religious sites', 'Cover shoulders and knees for mosques, churches and traditional shrines. Kampala streetwear is relaxed; sacred spaces are not.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Patience with time', 'Appointments can run late without anyone treating it as a crisis. Build buffer into plans, especially around Kampala traffic, and stay polite rather than pushing.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Public affection', 'Kampala is more relaxed than rural Uganda, but overt public affection still draws attention. A little discretion is the local default.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Right hand for exchange', 'Give and receive money, food and gifts with your right hand, or with both hands. The left hand is still considered less polite for that kind of exchange.', NULL, NULL, NULL, NULL, TRUE),
        ('ETIQUETTE', 'Tipping is a thank-you, not a bill', 'Tipping is appreciated rather than automatic. Rounding up a taxi fare, leaving 5–10% in a sit-down restaurant, or a small cash thank-you to a guide is typical.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'A young country', 'Uganda has one of the youngest populations in the world. That energy shows up in Kampala’s music, start-ups, nightlife and street food as much as in official statistics.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Boda boda origin', '“Boda boda” originally described border-to-border motorcycle taxis. In Kampala it now means almost any motorbike-for-hire weaving through traffic.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Equator crossing', 'The equator crosses Uganda just south of Kampala. Many travellers stop at the marked crossing on the Kampala–Masaka road for photos and the classic water-drain demonstration.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Fifty-plus languages', 'Uganda has more than 50 living languages. English is official, Swahili is a second official language, and Luganda is the one you will hear most around Kampala.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Lake Victoria scale', 'Lake Victoria is Africa’s largest lake by area. Entebbe sits on its northern shore, which is why the international airport feels more lakeside town than inland capital.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Mountain gorillas', 'Uganda is one of only a handful of countries where you can trek to see mountain gorillas, mainly in Bwindi Impenetrable National Park and Mgahinga in the south-west.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Pearl of Africa', 'Winston Churchill called Uganda the “Pearl of Africa” after travelling through East Africa in 1907 — the nickname still fits the lakes, hills and wildlife packed into a relatively small country.', NULL, NULL, NULL, NULL, TRUE),
        ('FUN_FACT', 'Source of the Nile', 'Jinja, on Lake Victoria, is widely recognised as the source of the Nile — the river then runs north through Uganda before continuing towards the Mediterranean.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Forex beats the hotel desk', 'Kampala forex bureaux on Kampala Road and around Nakasero usually beat hotel exchange rates. Count your notes at the window; reputable desks are used to visitors doing exactly that.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Leave Kampala before the Friday rush', 'If you are heading west to Queen Elizabeth or Bwindi, leave Kampala early on Friday — or better, Thursday. Weekend traffic on the Masaka road can erase a whole afternoon.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Murchison is closer than it feels', 'Murchison Falls is a long day from Kampala, but an overnight turns it from a rush into the classic Nile-and-savannah trip most first-time visitors actually want.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Owino for the real city', 'St. Balikuddembe Market (Owino) is chaotic, cheap and local. Go with a guide or a Kampala friend the first time; it is the opposite of a mall, and that is the point.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Share your live location on night rides', 'For late boda or taxi rides, share a live location with someone. It is normal caution rather than alarmism, and drivers used to visitors will not take offence.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Sim-sim and muchomo after dark', 'Roadside muchomo (grilled meat) and sim-sim (sesame) snacks appear as the sun drops. Follow the busiest stall rather than the quietest — turnover is your hygiene cue.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Sipi over the obvious waterfall stop', 'If you have a spare day in the east, Sipi Falls on the slopes of Mount Elgon is the overnight people remember — coffee tours, cliff views and cooler air than Kampala.', NULL, NULL, NULL, NULL, TRUE),
        ('INSIDER_TIP', 'Sunset at the lake, not the mall', 'For a first evening, skip the mall food court and go to a lakeside spot in Entebbe or Ggaba. Kampala’s hills are dramatic; the lake is where the day actually ends.', NULL, NULL, NULL, NULL, TRUE),
        ('PHRASE', 'Asante', 'Asante', 'Swahili for “thank you.” Asante sana means “thank you very much.” Handy beyond Kampala, especially towards Kenya and Tanzania.', 'sw', NULL, NULL, TRUE),
        ('PHRASE', 'Jambo', 'Jambo', 'A Swahili hello used across East Africa. English is more common in Kampala, but Jambo still works as a friendly, widely understood greeting.', 'sw', NULL, NULL, TRUE),
        ('PHRASE', 'Kale', 'Kale', 'A flexible Luganda yes / OK / alright. You will hear it constantly in Kampala conversation as agreement or a soft close to a discussion.', 'lg', NULL, NULL, TRUE),
        ('PHRASE', 'Mzungu', 'Mzungu', 'A Swahili-origin word for a foreigner, especially a white visitor. It is usually descriptive rather than hostile; a smile and a greeting still go a long way.', 'sw', NULL, NULL, TRUE),
        ('PHRASE', 'Oli otya?', 'Oli otya?', 'The everyday Luganda greeting: “How are you?” A typical reply is “Gyendi” (I’m fine). Using it, even once, usually gets a warmer response than jumping straight to English.', 'lg', NULL, NULL, TRUE),
        ('PHRASE', 'Ssebo and Nnyabo', 'Ssebo / Nnyabo', 'Polite Luganda forms of address: Ssebo for a man, Nnyabo for a woman. Useful with taxi drivers, market vendors and hotel staff.', 'lg', NULL, NULL, TRUE),
        ('PHRASE', 'Tusanyuse okukulaba', 'Tusanyuse okukulaba', '“We are happy to see you.” A warm welcome you may hear from hosts — worth recognising even if you do not say it yourself.', 'lg', NULL, NULL, TRUE),
        ('PHRASE', 'Webale', 'Webale', 'Luganda for “thank you.” Add “nyo” for “thank you very much”: Webale nyo.', 'lg', NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Agree the boda fare first', 'Agree the fare before you sit on a boda boda. Ride-hailing apps (SafeBoda, Uber, Bolt) remove most of that negotiation in Kampala and keep a record of the trip.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Buy a local SIM on arrival', 'MTN and Airtel kiosks sit just after baggage reclaim at Entebbe. Bring your passport. Data is inexpensive and coverage is strong in Kampala and major towns.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Cash still matters', 'Cards work in many hotels, restaurants and supermarkets in Kampala. Carry some Ugandan shillings anyway — markets, bodas and smaller eateries are still cash-first.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Drink bottled or treated water', 'Stick to sealed bottled water or a filter bottle. Ice in established restaurants is usually fine; be more cautious with street-side juices if you have a sensitive stomach.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Entebbe to Kampala takes longer than the map suggests', 'The airport is about 40 km from Kampala. In light traffic that can be 45–60 minutes; in the evening peak it can double. Build slack around flight times.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Mobile money is everywhere', 'MTN MoMo and Airtel Money booths are on almost every Kampala street. Locals use them for everything from school fees to market stalls. Visitors can often pay a vendor who then pays onward by mobile money.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Pack a Type G adapter', 'Uganda uses Type G sockets (the UK three-pin) at 240 V. A single adapter covers hotels, offices and most guesthouses.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Two rainy seasons, not a monsoon', 'Kampala’s wetter months are roughly March–May and September–November. Rain often arrives as a heavy burst rather than an all-day washout — a light jacket still earns its bag space.', NULL, NULL, NULL, NULL, TRUE),
        ('PRACTICAL_TIP', 'Yellow fever certificate', 'A yellow fever vaccination certificate is commonly requested on entry. Keep it with your passport rather than packed in hold luggage.', NULL, NULL, NULL, NULL, TRUE)
)
INSERT INTO local_knowledge (
    country_code,
    local_knowledge_type_id,
    title,
    content,
    explanation,
    local_language_code,
    geographic_area_id,
    source_url,
    is_live
)
SELECT
    'UG',
    t.id,
    i.title,
    i.content,
    i.explanation,
    i.language_code,
    a.id,
    i.source_url,
    i.is_live
FROM items i
JOIN local_knowledge_types t ON t.code = i.type_code
LEFT JOIN geographic_areas a ON a.code = i.area_code
WHERE NOT EXISTS (
    SELECT 1
    FROM local_knowledge existing
    WHERE existing.country_code = 'UG'
      AND existing.title = i.title
);

WITH links (title, tag_code) AS (
    VALUES
        ('Buganda hospitality', 'CULTURE'),
        ('Buganda hospitality', 'HISTORY'),
        ('Church and mosque side by side', 'CULTURE'),
        ('Kampala after dark', 'CULTURE'),
        ('Kampala after dark', 'NIGHTLIFE'),
        ('Markets set the price conversation', 'MONEY'),
        ('Markets set the price conversation', 'SHOPPING'),
        ('Matooke on the table', 'CULTURE'),
        ('Matooke on the table', 'FOOD'),
        ('Tea and coffee country', 'CULTURE'),
        ('Tea and coffee country', 'FOOD'),
        ('The Rolex is not a watch', 'CULTURE'),
        ('The Rolex is not a watch', 'FOOD'),
        ('Ask before photographing people', 'CULTURE'),
        ('Ask before photographing people', 'ETIQUETTE'),
        ('Greet before you ask', 'CULTURE'),
        ('Greet before you ask', 'ETIQUETTE'),
        ('Modest dress at religious sites', 'CULTURE'),
        ('Modest dress at religious sites', 'ETIQUETTE'),
        ('Patience with time', 'ETIQUETTE'),
        ('Patience with time', 'GETTING_AROUND'),
        ('Public affection', 'ETIQUETTE'),
        ('Right hand for exchange', 'ETIQUETTE'),
        ('Right hand for exchange', 'MONEY'),
        ('Tipping is a thank-you, not a bill', 'ETIQUETTE'),
        ('Tipping is a thank-you, not a bill', 'MONEY'),
        ('Tipping is a thank-you, not a bill', 'PAYMENTS'),
        ('A young country', 'CULTURE'),
        ('Boda boda origin', 'TRANSPORT'),
        ('Equator crossing', 'GETTING_AROUND'),
        ('Fifty-plus languages', 'LANGUAGE'),
        ('Lake Victoria scale', 'ARRIVAL'),
        ('Mountain gorillas', 'CULTURE'),
        ('Pearl of Africa', 'CULTURE'),
        ('Pearl of Africa', 'HISTORY'),
        ('Source of the Nile', 'HISTORY'),
        ('Forex beats the hotel desk', 'MONEY'),
        ('Leave Kampala before the Friday rush', 'GETTING_AROUND'),
        ('Leave Kampala before the Friday rush', 'TRANSPORT'),
        ('Murchison is closer than it feels', 'GETTING_AROUND'),
        ('Owino for the real city', 'SHOPPING'),
        ('Share your live location on night rides', 'SAFETY'),
        ('Share your live location on night rides', 'TRANSPORT'),
        ('Sim-sim and muchomo after dark', 'FOOD'),
        ('Sim-sim and muchomo after dark', 'NIGHTLIFE'),
        ('Sipi over the obvious waterfall stop', 'GETTING_AROUND'),
        ('Sunset at the lake, not the mall', 'FOOD'),
        ('Sunset at the lake, not the mall', 'NIGHTLIFE'),
        ('Asante', 'ETIQUETTE'),
        ('Asante', 'LANGUAGE'),
        ('Jambo', 'LANGUAGE'),
        ('Kale', 'LANGUAGE'),
        ('Mzungu', 'CULTURE'),
        ('Mzungu', 'LANGUAGE'),
        ('Oli otya?', 'ETIQUETTE'),
        ('Oli otya?', 'LANGUAGE'),
        ('Ssebo and Nnyabo', 'ETIQUETTE'),
        ('Ssebo and Nnyabo', 'LANGUAGE'),
        ('Tusanyuse okukulaba', 'CULTURE'),
        ('Tusanyuse okukulaba', 'LANGUAGE'),
        ('Webale', 'ETIQUETTE'),
        ('Webale', 'LANGUAGE'),
        ('Agree the boda fare first', 'GETTING_AROUND'),
        ('Agree the boda fare first', 'SAFETY'),
        ('Agree the boda fare first', 'TRANSPORT'),
        ('Buy a local SIM on arrival', 'ARRIVAL'),
        ('Buy a local SIM on arrival', 'CONNECTIVITY'),
        ('Cash still matters', 'MONEY'),
        ('Cash still matters', 'PAYMENTS'),
        ('Drink bottled or treated water', 'HEALTH'),
        ('Entebbe to Kampala takes longer than the map suggests', 'ARRIVAL'),
        ('Entebbe to Kampala takes longer than the map suggests', 'TRANSPORT'),
        ('Mobile money is everywhere', 'MOBILE_MONEY'),
        ('Mobile money is everywhere', 'PAYMENTS'),
        ('Pack a Type G adapter', 'ACCOMMODATION'),
        ('Two rainy seasons, not a monsoon', 'WEATHER'),
        ('Yellow fever certificate', 'ARRIVAL'),
        ('Yellow fever certificate', 'HEALTH')
)
INSERT INTO local_knowledge_tag_links (local_knowledge_id, tag_id)
SELECT lk.id, tg.id
FROM links
JOIN local_knowledge lk ON lk.country_code = 'UG' AND lk.title = links.title
JOIN local_knowledge_tags tg ON tg.code = links.tag_code
ON CONFLICT DO NOTHING;

WITH links (title, context_code) AS (
    VALUES
        ('Buganda hospitality', 'GUIDE_ESSENTIALS'),
        ('Buganda hospitality', 'GUIDE_REGION'),
        ('Buganda hospitality', 'HOME'),
        ('Church and mosque side by side', 'GUIDE_ESSENTIALS'),
        ('Church and mosque side by side', 'HOME'),
        ('Kampala after dark', 'HOME'),
        ('Kampala after dark', 'LISTING_DETAIL'),
        ('Markets set the price conversation', 'GUIDE'),
        ('Markets set the price conversation', 'HOME'),
        ('Matooke on the table', 'GUIDE_ESSENTIALS'),
        ('Matooke on the table', 'HOME'),
        ('Tea and coffee country', 'GUIDE_REGION'),
        ('Tea and coffee country', 'HOME'),
        ('The Rolex is not a watch', 'GUIDE'),
        ('The Rolex is not a watch', 'HOME'),
        ('Ask before photographing people', 'GUIDE_TRAVEL_GUIDE'),
        ('Ask before photographing people', 'HOME'),
        ('Greet before you ask', 'GUIDE_TRAVEL_GUIDE'),
        ('Greet before you ask', 'HOME'),
        ('Modest dress at religious sites', 'GUIDE_TRAVEL_GUIDE'),
        ('Modest dress at religious sites', 'HOME'),
        ('Patience with time', 'GUIDE'),
        ('Patience with time', 'HOME'),
        ('Public affection', 'HOME'),
        ('Right hand for exchange', 'GUIDE'),
        ('Right hand for exchange', 'HOME'),
        ('Tipping is a thank-you, not a bill', 'GUIDE_TRAVEL_GUIDE'),
        ('Tipping is a thank-you, not a bill', 'HOME'),
        ('A young country', 'GUIDE_ESSENTIALS'),
        ('A young country', 'HOME'),
        ('Boda boda origin', 'GUIDE_TRAVEL_GUIDE'),
        ('Boda boda origin', 'HOME'),
        ('Equator crossing', 'GUIDE'),
        ('Equator crossing', 'HOME'),
        ('Fifty-plus languages', 'GUIDE_ESSENTIALS'),
        ('Fifty-plus languages', 'HOME'),
        ('Lake Victoria scale', 'GUIDE_REGION'),
        ('Lake Victoria scale', 'HOME'),
        ('Mountain gorillas', 'GUIDE_REGION'),
        ('Mountain gorillas', 'HOME'),
        ('Pearl of Africa', 'GUIDE_ESSENTIALS'),
        ('Pearl of Africa', 'GUIDE_OVERVIEW'),
        ('Pearl of Africa', 'HOME'),
        ('Source of the Nile', 'GUIDE_REGION'),
        ('Source of the Nile', 'HOME'),
        ('Forex beats the hotel desk', 'GUIDE_TRAVEL_GUIDE'),
        ('Forex beats the hotel desk', 'HOME'),
        ('Leave Kampala before the Friday rush', 'GUIDE_REGION'),
        ('Leave Kampala before the Friday rush', 'HOME'),
        ('Leave Kampala before the Friday rush', 'TRIP_PLANNER'),
        ('Murchison is closer than it feels', 'GUIDE_REGION'),
        ('Murchison is closer than it feels', 'HOME'),
        ('Murchison is closer than it feels', 'TRIP_PLANNER'),
        ('Owino for the real city', 'DISCOVER'),
        ('Owino for the real city', 'HOME'),
        ('Share your live location on night rides', 'GUIDE_TRAVEL_GUIDE'),
        ('Share your live location on night rides', 'HOME'),
        ('Sim-sim and muchomo after dark', 'HOME'),
        ('Sim-sim and muchomo after dark', 'LISTING_DETAIL'),
        ('Sipi over the obvious waterfall stop', 'GUIDE_REGION'),
        ('Sipi over the obvious waterfall stop', 'HOME'),
        ('Sipi over the obvious waterfall stop', 'TRIP_PLANNER'),
        ('Sunset at the lake, not the mall', 'GUIDE_REGION'),
        ('Sunset at the lake, not the mall', 'HOME'),
        ('Asante', 'HOME'),
        ('Jambo', 'GUIDE_ESSENTIALS'),
        ('Jambo', 'HOME'),
        ('Kale', 'GUIDE'),
        ('Kale', 'HOME'),
        ('Mzungu', 'GUIDE'),
        ('Mzungu', 'HOME'),
        ('Oli otya?', 'GUIDE'),
        ('Oli otya?', 'HOME'),
        ('Ssebo and Nnyabo', 'GUIDE'),
        ('Ssebo and Nnyabo', 'HOME'),
        ('Tusanyuse okukulaba', 'HOME'),
        ('Webale', 'GUIDE_ESSENTIALS'),
        ('Webale', 'HOME'),
        ('Agree the boda fare first', 'GUIDE_TRAVEL_GUIDE'),
        ('Agree the boda fare first', 'HOME'),
        ('Buy a local SIM on arrival', 'GUIDE_TRAVEL_GUIDE'),
        ('Buy a local SIM on arrival', 'HOME'),
        ('Cash still matters', 'GUIDE_ESSENTIALS'),
        ('Cash still matters', 'GUIDE_TRAVEL_GUIDE'),
        ('Cash still matters', 'HOME'),
        ('Drink bottled or treated water', 'GUIDE_TRAVEL_GUIDE'),
        ('Drink bottled or treated water', 'HOME'),
        ('Entebbe to Kampala takes longer than the map suggests', 'GUIDE_REGION'),
        ('Entebbe to Kampala takes longer than the map suggests', 'GUIDE_TRAVEL_GUIDE'),
        ('Entebbe to Kampala takes longer than the map suggests', 'HOME'),
        ('Mobile money is everywhere', 'GUIDE_TRAVEL_GUIDE'),
        ('Mobile money is everywhere', 'HOME'),
        ('Pack a Type G adapter', 'GUIDE_ESSENTIALS'),
        ('Pack a Type G adapter', 'GUIDE_TRAVEL_GUIDE'),
        ('Pack a Type G adapter', 'HOME'),
        ('Two rainy seasons, not a monsoon', 'GUIDE_TRAVEL_GUIDE'),
        ('Two rainy seasons, not a monsoon', 'HOME'),
        ('Yellow fever certificate', 'GUIDE_TRAVEL_GUIDE'),
        ('Yellow fever certificate', 'GUIDE_TRAVEL_INFORMATION'),
        ('Yellow fever certificate', 'HOME')
)
INSERT INTO local_knowledge_page_contexts (local_knowledge_id, page_context_id)
SELECT lk.id, pc.id
FROM links
JOIN local_knowledge lk ON lk.country_code = 'UG' AND lk.title = links.title
JOIN page_contexts pc ON pc.code = links.context_code
ON CONFLICT DO NOTHING;

COMMIT;
